### PR TITLE
Update css of sidebar, site and about

### PR DESCRIPTION
**Pull request by bobwxc**
Use small round corner design.
looks like 
Screenshot
now

### CODE REVIEW

**Comment by bobwxc** [comment]
The part of list and iso will be done later.

**Review by ZenithalHourlyRate — CHANGES_REQUESTED** [review]
I personally dislike rounded corner and margin in closely placed buttons. You may add colorred border instead. 

When adding color, both dark/light mode should be considerred. In the case of this PR, I would like the background color of `site-content` to be not changed.

Also I personally dislike too much animation (transition).

**Comment by bobwxc** [comment]
既然已经采用方块阴影层级设计，那么此pr关闭

**Comment by ZenithalHourlyRate** [comment]
In 142f9aff76bf86a0695315631e568ed68ca2eca6 part of your commit is picked

**Comment by bobwxc** [comment]
> In [142f9af](https://github.com/tuna/mirrorz/commit/142f9aff76bf86a0695315631e568ed68ca2eca6) part of your commit is picked

Got that, Thanks!

**Pull request closed without merging**
