### PR TITLE
Add xtom mirrors

### PR DESCRIPTION
**Pull request by taoky**
Changes:
- Add "ustclug-v1" parser, which parse mirrorz data from ustcmirror HTML index & yuki JSON metas.
- Add [xtom](https://mirrors.xtom.com) & [xtom-hk](https://mirrors.xtom.com.hk) to mirrorz mirrorlist.

CC: @showfom

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
By the way, related to #31 since xtom homepage is fetched via reverse proxy.

**Review by ZenithalHourlyRate — APPROVED** [review]
It would be be

**Comment by Showfom** [comment]
Please also add the following mirrors

mirrors.xtom.de - Germany
mirrors.xtom.nl - Netherlands
mirrors.xtom.ee - Estonia

Our HK mirror is not accessible from China Mainland because of high abuse from CN IPs these days :(

**Comment by taoky** [comment]
> Our HK mirror is not accessible from China Mainland because of high abuse from CN IPs these days :(

Do I need to remove HK mirror from this PR?

**Comment by Showfom** [comment]
> 
> 
> > Our HK mirror is not accessible from China Mainland because of high abuse from CN IPs these days :(
> 
> Do I need to remove HK mirror from this PR?

Yes you can remove our HK mirror

**Comment by ZenithalHourlyRate** [comment]
@Showfom `https://mirrors.xtom{.com.hk,.ee,.de}/api/v1/metas` are not available yet, please add them when you have time.

Meanwhile `https://mirrors.xtom{.com,.nl}/api/v1/metas` has `access-control-allow-origin` set to `''`, which causes the following error.
```
Access to fetch at 'https://mirrors.xtom.nl/api/v1/metas' from origin 'https://mirrorz.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value ''.
```

Please set `access-control-allow-origin` to `*` or `https://mirrorz.org`  when the referer is `https://mirrorz.org/` for all these mirrors.

**Comment by shankerwangmiao** [comment]
> @Showfom `https://mirrors.xtom{.com.hk,.ee,.de}/api/v1/metas` are not available yet, please add them when you have time.
> 
> Meanwhile `https://mirrors.xtom{.com,.nl}/api/v1/metas` has `access-control-allow-origin` set to `''`, which causes the following error.
> 
> ```
> Access to fetch at 'https://mirrors.xtom.nl/api/v1/metas' from origin 'https://mirrorz.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value ''.
> ```
> 
> Please set `access-control-allow-origin` to `*` or `https://mirrorz.org` when the referer is `https://mirrorz.org/` for all these mirrors.

It should be `Origin:` instead of `Referer`

Ref conf:

```
map $http_origin $is_good_origin {
  ~*([.|/]|^)mirrorz.org$ 1;
  default 0;
}
```

```
location xxxx {
  if ($is_good_origin) {
    add_header 'Access-Control-Allow-Origin' "$http_origin";
    add_header 'Vary' "Origin";
    add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-TUNA-MIRROR-ID';
  }

}
```

**Comment by Showfom** [comment]
I have forward the request to our mirror administrator.

**Review by ZenithalHourlyRate — APPROVED** [review]

**Comment by ZenithalHourlyRate** [comment]
While CORS is not ready, merging this PR would not lead to malfunctioning of the website

**Comment by ZenithalHourlyRate** [comment]
> I have forward the request to our mirror administrator.

`mirrors.xtom.{com,com.hk,de,nl}` have not set CORS accordingly yet.

**Comment by Showfom** [comment]
Fixed

**Pull request merged**
