### PR TITLE
add mirrorz-404.svg

### PR DESCRIPTION
**Pull request by bobwxc**
add mirrorz-404.svg for future 404 page's picture.

Used the original logo in the middle, and change the white part to transparent.
The two characters are hand drawn, not font.

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
> future 404 page's picture.

Currently `404.html` is used for redirection, how shall this img be used……

**Comment by bobwxc** [comment]
> Currently `404.html` is used for redirection, how shall this img be used……

I don't know. I'm only a little poor art worker ...
But now, when visit pages like mirrorz.org/xxxx, only got a almost blank page with bars.
Could we add somthing in the page center ?

**Comment by ZenithalHourlyRate** [comment]
Someone suggested adding some detail in the eye.
 

This PR will be accepted.

**Comment by bobwxc** [comment]
added a pupil and highlight

**Comment by ZenithalHourlyRate** [comment]
Try https://mirrorz.org/os/bobwxc and https://mirrorz.org/os

**Comment by bobwxc** [comment]
在 2021/2/14 下午6:52, Zenithal 写道:
>
> Try https://mirrorz.org/os/bobwxc <https://mirrorz.org/os/bobwxc> and 
> https://mirrorz.org/os <https://mirrorz.org/os>
>
Both good, Thanks.

And please visit https://mirrorz.org/Zenithal and you will get a
     "Select one Zenithal from the sidebar"


-- 
bobwxc
2BF2 A4AA 2F07 30C3 279E  D01D 3268 4A40 BCA7 AEA7

**Pull request merged**
